# Generated by Django 5.2.3 on 2025-07-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
