# Generated by Django 5.2.3 on 2025-07-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_specs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specs',
        ),
    ]
